### PR TITLE
还原

### PR DESCRIPTION
**Pull request by mapleshadow**

### CODE REVIEW

**Comment by mapleshadow** [comment]
还原更新

**Comment by derekslenk** [comment]
Please don't accept this merge unless we can add language localization

**Comment by mapleshadow** [comment]
sorry....

2013/6/25 Derek Slenk notifications@github.com

> Please don't accept this merge unless we can add language localization
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hardcpp/P2PoolExtendedFrontEnd/pull/16#issuecomment-19985457
> .

## 

—枫影—

**Comment by hardcpp** [comment]
please dont remove credits at bottom

**Comment by mapleshadow** [comment]
OK

2013/6/27 HardCPP notifications@github.com

> please dont remove credits at bottom
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hardcpp/P2PoolExtendedFrontEnd/pull/16#issuecomment-20088206
> .

## 

—枫影—

**Pull request closed without merging**
